In [18]:
#Upload the raw dataset into Google Colab
from google.colab import files

#Import pandas for data cleaning and manipulation
import pandas as pd

uploaded = files.upload()

#Load the raw dataset into a DataFrame
df = pd.read_csv("raw_frailty_data.csv", encoding="latin1")

#Preview the first five rows
df.head()

Saving raw_frailty_data.csv to raw_frailty_data.csv

  Height  Weight  Age  Grip strength  Frailty
0   65.8     112   30             30        N
1   71.5     136   19             31        N
2   69.4     153   45             29        N
3   68.2     142   22             28        Y
4   67.8     144   29             24        Y

In [19]:
#Look over dataset structure and types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Height          10 non-null     object
 1   Weight          10 non-null     object
 2   Age             10 non-null     object
 3   Grip strength   10 non-null     object
 4   Frailty         10 non-null     object
dtypes: object(5)
memory usage: 532.0+ bytes

In [20]:
# Display summary statistics for the numerical variables
df.describe()

       Height  Weight  Age  Grip strength  Frailty
count       10      10   10             10       10
unique      10       8   10              9        2
top      65.8     112   30             31        N
freq         1       2    1              2        6

In [21]:
# Display the data type of each variable
df.dtypes

Height            object
Weight            object
Age               object
Grip strength     object
Frailty           object
dtype: object

In [22]:
# View column names in the dataset
df.columns

Index(['Height ', 'Weight ', 'Age ', 'Grip strength ', 'Frailty '], dtype='object')

In [23]:
# Remove extra spaces from column names
df.columns = df.columns.str.strip()

# Verify that extra spaces were removed from column names
print(df.columns)

Index(['Height', 'Weight', 'Age', 'Grip strength', 'Frailty'], dtype='object')

In [24]:
# Remove whitespace from numeric column values
df["Height"] = df["Height"].astype(str).str.replace(r"\s+", "", regex=True)
df["Weight"] = df["Weight"].astype(str).str.replace(r"\s+", "", regex=True)
df["Age"] = df["Age"].astype(str).str.replace(r"\s+", "", regex=True)
df["Grip strength"] = df["Grip strength"].astype(str).str.replace(r"\s+", "", regex=True)

In [25]:
# Convert numeric columns from object to numeric data types
df["Height"] = pd.to_numeric(df["Height"])
df["Weight"] = pd.to_numeric(df["Weight"])
df["Age"] = pd.to_numeric(df["Age"])
df["Grip strength"] = pd.to_numeric(df["Grip strength"])

In [26]:
# Verify that the data types were successfully converted
df.dtypes

Height           float64
Weight             int64
Age                int64
Grip strength      int64
Frailty           object
dtype: object

In [27]:
# Clean Frailty column before encoding
df["Frailty"] = df["Frailty"].astype(str).str.strip().str.upper()

In [28]:
# Verify Frailty values are standardized to Y and N
df["Frailty"].unique()

array(['N', 'Y'], dtype=object)

In [29]:
# Check for missing values in each column
df.isnull().sum()

Height           0
Weight           0
Age              0
Grip strength    0
Frailty          0
dtype: int64

In [30]:
# Check for duplicate rows
df.duplicated().sum()

np.int64(0)

In [31]:
# Verify the dataset shape before and after removing missing values
print("Before:", df.shape)
df = df.dropna()
print("After:", df.shape)

Before: (10, 5)
After: (10, 5)

In [32]:
# Save cleaned dataset as a CSV file
df.to_csv("frailty_data_clean.csv", index=False)

In [33]:
# Download the cleaned dataset
from google.colab import files
files.download("frailty_data_clean.csv")