In [2]:
#UPLOADED FILE IN GOOGLE COLAB
from google.colab import files

uploaded = files.upload()

Saving raw_frailty_data.csv to raw_frailty_data.csv

In [3]:
#IMPORTED PANDAS TO LOOK AT THE DATA ANALYSIS LIBRARY
import pandas as pd

#LOADED RAW DATA
df = pd.read_csv("raw_frailty_data.csv", encoding="latin1")

df.head()

  Height  Weight  Age  Grip strength  Frailty
0   65.8     112   30             30        N
1   71.5     136   19             31        N
2   69.4     153   45             29        N
3   68.2     142   22             28        Y
4   67.8     144   29             24        Y

In [4]:
#LOOKED OVER INFO OF THE DATA
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Height          10 non-null     object
 1   Weight          10 non-null     object
 2   Age             10 non-null     object
 3   Grip strength   10 non-null     object
 4   Frailty         10 non-null     object
dtypes: object(5)
memory usage: 532.0+ bytes

In [5]:
#LOOKED OVER STATISTICALLY INFO OF THE DATA
df.describe()

       Height  Weight  Age  Grip strength  Frailty
count       10      10   10             10       10
unique      10       8   10              9        2
top      65.8     112   30             31        N
freq         1       2    1              2        6

In [6]:
#DATA TYPES
df.dtypes

Height            object
Weight            object
Age               object
Grip strength     object
Frailty           object
dtype: object

In [7]:
#COLUMN NAMES
df.columns

Index(['Height ', 'Weight ', 'Age ', 'Grip strength ', 'Frailty '], dtype='object')

In [8]:
#REMOVE EXTRA SPACES
df.columns = df.columns.str.strip()

In [9]:
#VERIFIED EXTRAS WERE REMOVED
print(df.columns)

Index(['Height', 'Weight', 'Age', 'Grip strength', 'Frailty'], dtype='object')

In [17]:
#CLEAN COLUMN NAMES
df.columns = df.columns.str.strip()

#REMOVE ALL WHITESPACE FROM NUMERIC COLUMNS
df["Height"] = df["Height"].astype(str).str.replace(r"\s+", "", regex=True)
df["Weight"] = df["Weight"].astype(str).str.replace(r"\s+", "", regex=True)
df["Age"] = df["Age"].astype(str).str.replace(r"\s+", "", regex=True)
df["Grip strength"] = df["Grip strength"].astype(str).str.replace(r"\s+", "", regex=True)

In [18]:
#COVERT OBJECT (D.TYPES) TO NUMBERIC (D.TYPES)
df["Height"] = pd.to_numeric(df["Height"])
df["Weight"] = pd.to_numeric(df["Weight"])
df["Age"] = pd.to_numeric(df["Age"])
df["Grip strength"] = pd.to_numeric(df["Grip strength"])

In [19]:
#VERIFIED D.TYPES WERE CONVERTED
df.dtypes

Height           float64
Weight             int64
Age                int64
Grip strength      int64
Frailty           object
dtype: object

In [20]:
##CLEAN FRAILTY COLUMN BEFORE ENCODING
df["Frailty"] = df["Frailty"].astype(str).str.strip().str.upper()

In [21]:
#VERIFY FRAILTY VALUES ARE STANDARDIZED TO Y AND N
df["Frailty"].unique()

array(['N', 'Y'], dtype=object)

In [23]:
#CHECK FOR MISSING VALUES IN FRAILTY COLUMN
df["Frailty"].isna().sum()

np.int64(0)

In [24]:
#CHECKED FOR NULLS
df.isnull().sum()

Height           0
Weight           0
Age              0
Grip strength    0
Frailty          0
dtype: int64

In [25]:
#CHECKED FOR DUPLICATES
df.duplicated().sum()

np.int64(0)

In [26]:
#CHECKED FOR MISSING VALUES
df.dropna()

   Height  Weight  Age  Grip strength Frailty
0    65.8     112   30             30       N
1    71.5     136   19             31       N
2    69.4     153   45             29       N
3    68.2     142   22             28       Y
4    67.8     144   29             24       Y
5    68.7     123   50             26       N
6    69.8     141   51             22       Y
7    70.1     136   23             20       Y
8    67.9     112   17             19       N
9    66.8     120   39             31       N

In [27]:
#PROOF OF NO MISSING VALUES
print("Before:", df.shape)

df = df.dropna()

print("After:", df.shape)

Before: (10, 5)
After: (10, 5)

In [28]:
df.to_csv("frailty_data_clean.csv", index=False)

In [32]:
from google.colab import files
files.download("frailty_data_clean.csv")